# Generated by Django 5.1.3 on 2024-12-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('general_knowledge', 'General Knowledge'), ('music', 'Music'), ('sports', 'Sports'), ('other', 'Other')], default='general_knowledge', max_length=50),
        ),
    ]
