# Generated by Django 5.1.4 on 2024-12-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_location_alter_quiz_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
