// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class T1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void t1() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1050, 1002));
    driver.findElement(By.linkText("Register here")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > input")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > input")).sendKeys("test");
    driver.findElement(By.cssSelector("div:nth-child(2) > input")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > input")).sendKeys("test@mail.com");
    driver.findElement(By.cssSelector("div:nth-child(3) > input")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) > input")).sendKeys("sifra");
    driver.findElement(By.cssSelector("div:nth-child(4) > input")).click();
    driver.findElement(By.cssSelector("div:nth-child(4) > input")).sendKeys("sifra");
    driver.findElement(By.cssSelector("select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("select"));
      dropdown.findElement(By.xpath("//option[. = 'User']")).click();
    }
    driver.findElement(By.cssSelector("button:nth-child(6)")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("p:nth-child(2)")));
    }
    assertThat(driver.findElement(By.cssSelector("p:nth-child(2)")).getText(), is("An error occurred"));
  }
}
